// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./components/header.vue')['default']
    Icon: typeof import('./components/icon.vue')['default']
    IconApp: typeof import('./components/icon-app.vue')['default']
  }
}

export { }
